// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"p8/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: loginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Example},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/users/id/:userId",
					Handler: GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/users/create",
					Handler: CreateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/id/:id",
					Handler: GetByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/all",
					Handler: GetAllHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/user/update/id",
					Handler: UpdateByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/user/delete/id",
					Handler: DeleteByIdHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
